version: '3'
services:
  db:
    image: postgres:10-alpine
    volumes:
      - database:/var/lib/postgresql/data/
    ports:
      - 5432:5432
  app:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
    depends_on:
      - db
    ports:
      - 8000:8000

volumes:
  database: